version: '3.8'

services:
  whatsapp-analyzer:
    build: .
    container_name: whatsapp-analyzer
    ports:
      - "8501:8501"  # Streamlit
      - "8000:8000"  # FastAPI
    volumes:
      - ./reports:/app/reports
      - ./exports:/app/exports
      - ./temp:/app/temp
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    
  # Optional: Add Redis for session management in production
  redis:
    image: redis:alpine
    container_name: whatsapp-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
